language: node_js
sudo: false
node_js:
- '7'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - DEBUG='stats-collector:* test* -babel'
  - CXX=g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  irc:
    channels:
    - secure: 'QmNmyJANPglyK9EobrW+whJvRtk3VKRSxhk5JnTPJkUyEUw2FKcRZThRtAfjceGNPaRk1bm/l2OyUs/MpgkquFIQYpVlAzM3a5Lp9uxeUbopzmBFW2ccu4YWU+5auEtJm8rILRpVRxC34D8STodUwKTo2rBywOoaBXCrDsXkpfOCeEOa3fUXHcu0ENxq2BAWC6xJc4bYjAIcTlDrqedjDa+vIvitHyQw6463p/Uv1jrMb/jXo7496C2jyBWWQE+NeMeGEO/0KydTkfoDzFGPRNAty5DOCM8PirZRxG3lkrTg5oPg66+V+yVMsf1Vay591MsOxJDYs8ppWC9nrv8jlOJ++gbViR7/V0B5z3Rk0N+/FJR+6ykvSdY4fShdVLFY2yYSdm9HGYiWg4sV0ULCz7O2mux48LuJDWoVkWMuiMzMWLAbEcSF0hEboovlniHIk7joWllXp2nrI7uFuGnjsdbEw3HUGJFtLTa0+Cel4YpDaaF9l66rDQ4hwlnXi80Hl88gIuxbkRoow1OiNaQWcB4L4hEVBEzc3cMA68wZBJFZ7eWKKg4Ih5du+6eT+FxpP+0nq92ypS7sWvFy1Uc53FZ1ElAKN7GjIK+b32Cv3ktf15iE5qa0UcOZBAWPGbIJrjlUfkbGhQ72R/fSx2cHC76Dchhy5A1M7ZVIhnGhL1w='
    on_success: change
    on_failure: always
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
